version: '3.8'

services:
  consul-service:
    image: hashicorp/consul:1.20.0
    container_name: consul-server-bootstrap
    ports:
      - "8600:8600"
      - "8500:8500"
    volumes:
      - ./add_kv.sh:/usr/local/bin/add_kv.sh
      - ./features.json:/usr/local/bin/features.json
    command: "agent -server -bootstrap -ui -client=0.0.0.0"

    restart: unless-stopped
    networks:
      - consul-network

networks:
  consul-network:
    driver: bridge